name: news-bot

on:
  schedule:
    - cron: '0 6 * * *'   # раз в день в 06:00 UTC
  workflow_dispatch:

concurrency:
  group: news-${{ github.ref }}
  cancel-in-progress: true

jobs:
  send-news:
    runs-on: ubuntu-24.04
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
      TEXT: "News"
    steps:
      - name: send telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="${TEXT}" \
            -d message_thread_id="${THREAD_ID}" \
            -d parse_mode="Markdown"
